spring:
  data:
    mongodb:
      uri: mongodb+srv://hytejasvi:kftNgfGdLJTc15MX@cluster0.puhyu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: taskmanager
      auto-index-creation : true

#logging:
#  level:
#    com:
#      hytejasvi:
#        journalApp: DEBUG

#Logging levels: trace--> Debug--> Info--> Warn --> error
#by default, info and below are enabled, we need to particularly enable the above levels if needed
# if we set logging level as debug, then debug and it's below levels are enabled / allowed.